### PR TITLE
Replace google search by algolia docsearch

### LINKED ISSUE #69: Better Search

### PR DESCRIPTION
**Pull request by ujovlado**
Fixes #69 

Chages:

- install algolia doc search
- remove google search results page

### CODE REVIEW

**Comment by ujovlado** [comment]
@odinuv kukni to ... ak voci tomu nemas vyhrady, rovnako by som to nasadil aj na connection-docs ;)

**Comment by ujovlado** [comment]
:100:

**Comment by Halama** [comment]
Taky vidíte tohle?
image

**Comment by ujovlado** [comment]
@Halama este chvilku, je tam 10 min cache

**Comment by odinuv** [comment]
jop, je to nejaky jebly`

**Pull request merged**
