### PR TITLE
Update deployment.md

### PR DESCRIPTION
**Pull request by ondrejhlavacek**
Nahradil jsem `KBC_APP_REPOSITORY` za ~DOCKER_APP_IMAGE~ `APP_IMAGE`, což mi přijde jako trochu smysluplnější název. Možná to ještě není 100%, tak prosím o review :-)

### CODE REVIEW

**Comment by pivnicek** [comment]
+1 I regretted using `KBC_APP_REPOSITORY` from the beginning, but had put it everywhere already:)

**Comment by ondrejhlavacek** [comment]
@pivnicek where is the everywhere? we can change it :-)

**Comment by pivnicek** [comment]
@ondrejhlavacek just in the db extractors and demo app.  it's not too bad, will change it next time when a travis update is required :-)

**Comment by odinuv** [comment]
allso here https://github.com/keboola/docs-deploy-example and here https://github.com/keboola/docs-deploy-example-tests

**Comment by ondrejhlavacek** [comment]
@odinuv thanks, here it is 

https://github.com/keboola/docs-deploy-example-tests/pull/1
https://github.com/keboola/docs-deploy-example/pull/1

I am still not sure about `DOCKER_APP_IMAGE` or `DOCKER_IMAGE` or `APP_IMAGE` or something else? :-)

**Comment by pivnicek** [comment]
hmm,  I vote for `APP_IMAGE`

**Comment by odinuv** [comment]
takze vyhrava APP_IMAGE :)

**Comment by ondrejhlavacek** [comment]
Koukám, že Odinství už updatovalo ty `docs-*` repozitáře, upravil jsem ještě dokumentaci a u toho ještě změni `docker` na `Docker` v textech.

**Pull request merged**
