### PR TITLE
Add support of steps and steps groups to templates (KAC-94)

### PR DESCRIPTION
**Pull request by JakubMatejka**

### CODE REVIEW

**Review by webrouse — COMMENTED** [review]
Uprav prosim este tutorial:
https://developers.keboola.com/cli/templates/tutorial/#complete-user-inputs

**Review by webrouse — APPROVED** [review]
:+1: super

(mergnime to prosim az vydame novu verziu CLI)

**Comment by ujovlado** [comment]
@JakubMatejka  new default branch is `main`. Would it be possible to rebase this PR?

**Comment by ujovlado** [comment]
Aha, toto nie je z forku, rebasnem ja.

**Pull request merged**
